image: google/cloud-sdk:alpine

deploy-prod:
  stage: deploy
  script:

    - echo "Checking Service Account Key File"
    - ls -la $GCP_SERVICE_ACCOUNT_KEY
    - cat $GCP_SERVICE_ACCOUNT_KEY
    - gcloud auth activate-service-account --key-file="$GCP_SERVICE_ACCOUNT_KEY"
    # - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
    # - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
    - gcloud config set project pt-report
    - gcloud --quiet app deploy app.yaml

   
  environment: production
  only:
    - main
